---
- name: Remove existing app if present
  file: path=/Applications/{{app_name}}.app state=absent
- name: Copy {{app_name}} app to Applications directory
  command: cp -R "{{app_name}}.app" /Applications chdir={{downloads}}